jobs:
  test:
    name: Test Application
    needs:
      - format-check
      - lint

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/ckeckout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2
