# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: go-test

on:
  push:
    branches:
      - main
  #  tags:
  #    - v*
  # pull_request:
  #   branches:
  #     - main

permissions:
  contents: write

jobs:

  deploy-function:
    name: deploy faas
    runs-on: ubuntu-latest
    # needs: build-artifact
    # if ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: show checkout
        run: ls -R
      - id: auth
        name: auth
        uses: 'google-github-actions/auth@v1'
        with:
          # service_account: ${{ secrets.gcp_service_account }}
          credentials_json: ${{ secrets.gcp_credentials }}
      - id : deploy
        name: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: timeaway
          entry_point: GCPServer
          project_id: github-timeaway-399312
          runtime: go121
          # credentials: ${{ secrets.gcp_credentials }}
      - name: echo output
        run: 'echo "${{ steps.deploy.outputs.url }}"'
      - id: test
        run: 'curl "${{ steps.deploy.outputs.url }}/" | head -n 10'

