# https://github.com/golangci/golangci-lint-action

name: golangci-lint

# on:
#   push:
#     branches:
#       - main
#     pull_request:

# only run if the go-test workflow has run
on:
  workflow_run:
    workflows: ["go-test"]
  types:
    - completed

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - uses: actions/setup-go@v4 
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54




