# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: go-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3 # needed for cache
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: test
        run: go test -v ./...
        # run: make test
      # use this option to share coverage reports with team members
      # - name: coverage check
      #   run: make coverage
      # - name: make report
      #   run: make report
      # - name: copy files
      #   run: |
      #     mkdir reports
      #     cp cover.html reports/
      # - name: archive
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: reports
      #     path: reports

  # https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#example-not-requiring-successful-dependent-jobs
  golangci:
    needs: test  # requires test to be successful 
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - uses: actions/setup-go@v4 
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

  build-artifact:
    # https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
    needs: golangci
    name: artifacts
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3 # needed for cache
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true
      - name: build
        run: make build
      - name: Copy Files
        run: |
          mkdir artifacts
          cp timeaway artifacts/
      - name: archive
        uses: actions/upload-artifact@v3
        with:
          name: timeaway-linux-amd64
          path: artifacts/
          retention-days: 5

  release:
    # copy the artifact to a release
    name: release
    needs: build-artifact
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3 # needed for cache
      - name: download binary
        # https://github.com/actions/download-artifact
        # You can use the upload-artifact and download-artifact actions to share data between jobs in a workflow
        uses: actions/download-artifact@v3
        with:
          name: timeaway-linux-amd64
          path: artifacts/
      - name: show download
        run: ls -R
      - name: create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') # only if tagged
        with:
          files: artifacts/timeaway-linux-amd64
          draft: true
          body: test workflow release
          fail_on_unmatched_files: true
